from __future__ import annotations

from typing import Any, Protocol


class VideoProvider(Protocol):
    def get_capabilities(self) -> dict[str, Any]: ...
    def submit_generation(self, prompt: str, assets: list[str], parameters: dict[str, Any]) -> str: ...
    def get_task_status(self, task_id: str) -> dict[str, Any]: ...
    def download_result(self, task_id: str, output_path: str) -> str: ...
    def cancel_task(self, task_id: str) -> bool: ...
